# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plist',
            fields=[
                ('tfield', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purch_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('remarks', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=200)),
                ('responded', models.IntegerField(default=0)),
                ('placed', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0, null=True)),
                ('adm_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/static/image/'),
        ),
        migrations.AddField(
            model_name='plist',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
        migrations.AddField(
            model_name='plist',
            name='purch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Purchase'),
        ),
    ]
